
if(Execinfo_INCLUDE_DIR)
  set(Execinfo_INCLUDE_DIRS ${Execinfo_INCLUDE_DIR})
  if (Execinfo_LIBRARY)
    set(Execinfo_LIBRARIES ${Execinfo_LIBRARY})
  endif()
  set(Execinfo_FOUND TRUE)
  return()
endif()

find_path(Execinfo_INCLUDE_DIR NAMES execinfo.h)
find_library(Execinfo_LIBRARY NAMES execinfo)

if(Execinfo_INCLUDE_DIR)
  set(Execinfo_FOUND TRUE)
  set(Execinfo_INCLUDE_DIRS ${Execinfo_INCLUDE_DIR})
  if (Execinfo_LIBRARY)
    set(Execinfo_LIBRARIES ${Execinfo_LIBRARY})
    message(STATUS "Found Execinfo: ${Execinfo_INCLUDE_DIRS}, ${Execinfo_LIBRARIES}")
  else()
    message(STATUS "Found Execinfo: ${Execinfo_INCLUDE_DIRS}")
  endif()
else()
  if (Execinfo_FIND_REQUIRED)
    message(FATAL_ERROR "Execinfo not found.")  
  else()
    message(STATUS "Execinfo not found.")
  endif()
endif()

mark_as_advanced(Execinfo_INCLUDE_DIR Execinfo_LIBRARY)
