if(EXISTS "${DEST}")
  message(STATUS  "Up-to-date: ${DEST}")
else()
  find_program(OpenSSL_EXECUTABLE openssl)
  if(NOT OpenSSL_EXECUTABLE)
    message(STATUS "Bypassing : Unable to locate openssl to generate RSA certificate")
  else()
    message(STATUS "Generating: ${DEST}")
    execute_process(COMMAND openssl req -x509 -nodes -days 7300 -newkey rsa:1024 -keyout ${DEST} -out ${DEST}
                    INPUT_FILE ${CMAKE_CURRENT_LIST_DIR}/GenerateCertInput.txt OUTPUT_QUIET ERROR_QUIET)
    if(NOT EXISTS "${DEST}")
      message(WARNING "Error whie generating RSA key for TLS")
    endif()
  endif()
endif()
